# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tech-backend
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
    networks:
      - app-connect

  node:
    # image: ygorazambuja/tech-backend
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 3000:3000
    command: 'npm run start'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-connect

volumes:
  postgres-data:
networks:
  app-connect:
    driver: bridge
